# max Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: max
  template:
    metadata:
      labels:
        app: max
    spec:
      containers:
        - name: max
          image: kodexmachine/re-treat_app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: mysql-service  # Service name of the MySQL database
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
